export { default as AuthRoutes } from './auth.js'
export { default as OwnerRoutes } from './owner.js'
export { default as CategoryRoutes } from './category.js'
export { default as SubjectRoutes } from './subject.js'
export { default as DetailRoutes } from './detail.js'
export { default as TransactionRoutes } from './transaction.js'
export { default as ReportRoutes } from './report.js'
export { default as UploadRoutes } from './upload.js'
export { default as FileManagerRoutes} from './fileManager.js'
