export { default as AuthRoutes } from './auth.js'
export { default as DatabaseRoutes } from './databases.js'
export { default as OwnerRoutes } from './owner.js'
export { default as CategoryRoutes } from './category.js'
export { default as SubjectRoutes } from './subject.js'
export { default as DetailRoutes } from './detail.js'
export { default as TransactionRoutes } from './transaction.js'
export { default as TransactionImportAssociatedRoutes } from './transaction-import-associated.js'
export { default as ReportRoutes } from './report.js'
export { default as UploadRoutes } from './upload.js'
export { default as FileManagerRoutes} from './fileManager.js'
export { default as ScadenziarioRoutes } from './scadenziario.js'
export { default as AnomalieRoutes } from './anomalie.js'
export { default as ClassificationFeedbackRoutes } from './classification-feedback.js'
export { default as SmartClassifierRoutes } from './smart-classifier.js'
// export { default as GroupsRoutes } from './groups.js' // Disabled - using consultative approach in report.js
// export { default as SetupRoutes } from './setup.js'
// export { default as MLAnalysisRoutes } from './ml-analysis.js'
